import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '../styles/globals.css';
import '../styles/output.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { Box, MainLayout } from '@/components';
import React from 'react';
import { AuthProvider } from '@/providers';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Box className="overflow-x-hidden scrollbar-hide">
          <AuthProvider>
            <MainLayout>{children}</MainLayout>
          </AuthProvider>
        </Box>
        <ToastContainer />
      </body>
    </html>
  );
};

export default RootLayout;
