#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Checking ESlint errors ..."

cd projects/front
if git diff --cached --name-only | grep -E '^projects/front'
then
  echo "Changes detected in front. Checking ESlint errors..."

  npm run lint
fi

cd ../back
if git diff --cached --name-only | grep -E '^projects/back'
then
  echo "Changes detected in back. Checking ESlint errors..."

  npm run lint
fi

cd ../gui
if git diff --cached --name-only | grep -E '^projects/gui'
then
  echo "Changes detected in GUI. Checking ESlint errors..."

  npm run lint
fi