name: Create Preview Link for PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: cd projects/front && npm install

    - name: Vercel Deployment
      run: cd projects/front && npx vercel --token ${{ secrets.VERCEL_TOKEN }} --orgId ${{ secrets.VERCEL_ORG_ID }} --projectId ${{ secrets.VERCEL_PROJECT_ID }}
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
