name: Create Preview Link for PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Change to project directory
        run: cd projects/front

      - name: Create generated files
        run: npm run generate
        working-directory: projects/front

      - name: Deploy Project and Get Preview URL
        id: deploy
        run: |
          URL=$(vercel --token ${{ secrets.VERCEL_TOKEN }} | grep -Po '(?<=https://)[^ >]+(?=.vercel.app)')
          echo "::set-output name=preview_url::https://$URL"
        working-directory: projects/front

      - name: Comment Preview URL on PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Preview URL: ${{ steps.deploy.outputs.preview_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}