name: Create Preview Link for PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Install Vercel CLI
        run: cd projects/front && npm install --global vercel

      - name: Create generated files
        run: cd projects/front && npm run generate

      - name: Deploy Project
        run: cd projects/front && vercel --token ${{ secrets.VERCEL_TOKEN }}